// <auto-generated />
using System;
using AppSlider.Infrastructure.EntityFrameworkDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppSlider.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190821064515_AddAdvertiserEstablishmentRelationship")]
    partial class AddAdvertiserEstablishmentRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppSlider.Domain.Entities.Business.Advertiser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCreated");

                    b.HasKey("Id");

                    b.ToTable("Advertisers");
                });

            modelBuilder.Entity("AppSlider.Domain.Entities.Business.AdvertiserEstablishments", b =>
                {
                    b.Property<Guid>("IdAdvertiser");

                    b.Property<Guid>("IdEstablishment");

                    b.HasKey("IdAdvertiser", "IdEstablishment");

                    b.HasIndex("IdEstablishment");

                    b.ToTable("AdvertiserEstablishments");
                });
            modelBuilder.Entity("AppSlider.Domain.Entities.Business.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCreated");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

      
            modelBuilder.Entity("AppSlider.Domain.Entities.Business.AdvertiserEstablishments", b =>
                {
                    b.HasOne("AppSlider.Domain.Entities.Business.Advertiser", "Advertiser")
                        .WithMany("AdvertisersEstablishments")
                        .HasForeignKey("IdAdvertiser")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppSlider.Domain.Entities.Business.Establishment", "Establishment")
                        .WithMany("AdvertisersEstablishments")
                        .HasForeignKey("IdEstablishment")
                        .OnDelete(DeleteBehavior.Cascade);
                });

     
#pragma warning restore 612, 618
        }
    }
}
